

// CHALLENGE: MAKE ME A THERMOSTAT

// USER SETS THE DESIRED TEMPERATURE
  // USER INPUT SOMEHOW
    // CLICK, SELECTING PREEXISTING OPTIONS?
    // HTML SELECT BOX 
    
    //  DO THEY ENTER ANY TEMP?

    //  IF THEY SELECT A TEMP, HOW DO THEY DO THAT?

    //  ONCE THEY SELECT A TEMP, I NEED TO STORE IT SOMEHOW





// CHECK THE TEMPERATURE
  // INTERVAL?
  // TOLERANCE??

// CHECKS TEMPERATURE
  //  AND THEN
  // COMPARES IT TO THE DESIRED TEMPERATURE
    //  AND THEN
      // ADJUSTS THE TEMPERATURE
      // IF ACTUAL TEMP IS LESS THAN THE DESIRED
        // EMIT HEAT
      //  ELSE IF THE ACTUAL IS MORE THAN THE DESIRED
        //  COOL THAT SHIT DOWN

  // REPEAT? 